sec: spring-security-web-3.1.7.RELEASE.jar: CVE-2022-22978: remove of class RegexRequestMatcher leads to embedded saml service provider throws NoClassDefFoundError on repository start. cause is org.springframework.security.config.http.MatcherType has a class member of this type. fix is using an empty implementation of this class.